[workspace]
members = [
    "crates/bit_lex",
    "crates/bit_ast",
    "crates/bit_common",
    "crates/bit_parse",
    "crates/bit",
    "crates/bit_compile",
    "crates/bit_pm",
    "crates/bit_gen",
    "crates/bit_lint",
    "crates/bit_tests"
]
resolver = "3"
doctest = false
