[workspace]
members = [
    "crates/geko",
    "crates/geko_ast",
    "crates/geko_common",
    "crates/geko_lex",
    "crates/geko_parse",
    "crates/geko_rt",
    "crates/geko_sema",
    "crates/geko_tests",
]
resolver = "3"
