[workspace]
members = [
    "crates/bit",
    "crates/bit_ast",
    "crates/bit_common",
    "crates/bit_lex",
    "crates/bit_parse",
    "crates/bit_rt",
    "crates/bit_sema",
    "crates/bit_tests",
    "crates/bit_wasm",
]
resolver = "3"
