[package]
name = "bit_ast"
version = "0.1.0"
edition = "2024"

[dependencies]
bit_lex = { path = "../bit_lex" }
bit_common = { path = "../bit_common" }
ecow = "0.2.6"
miette = { git = "https://github.com/watt-rs/miette.git", features = ["fancy"] }
