[package]
name = "geko_sema"
version = "0.1.0"
edition = "2024"

[dependencies]
geko_ast = { path = "../geko_ast" }
miette = { git = "https://github.com/geko-rs/miette", features = ["fancy"] }
thiserror = "2.0.18"
geko_common = { path = "../geko_common" }
