[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
lexer = { path = "../lexer" }
miette = { git = "https://github.com/bit-rs/miette" }
thiserror = "2.0.18"
ast = { path = "../ast" }
