[package]
name = "geko_lex"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.2.2"
miette = { git = "https://github.com/geko-rs/miette", features = ["fancy"] }
thiserror = "2.0.18"
geko_common = { path = "../geko_common" }
