[lib]
crate-type = ["cdylib"]

[package]
name = "geko_wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.108"
geko_rt = { path = "../geko_rt" }
geko_common = { path = "../geko_common" }
camino = "1.2.2"
miette = { git = "https://github.com/geko-rs/miette", features = ["fancy"] }
