name: nightly-release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-freebsd
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo-tool: cargo
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cargo-tool: cross
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cargo-tool: cross
          - os: windows-2022
            target: x86_64-pc-windows-gnu
            cargo-tool: cross
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            cargo-tool: cargo
          - os: windows-2022
            target: aarch64-pc-windows-msvc
            cargo-tool: cargo
          - os: macos-latest
            target: x86_64-apple-darwin
            cargo-tool: cargo
          - os: macos-latest
            target: aarch64-apple-darwin
            cargo-tool: cargo
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
            cargo-tool: cargo

    steps:
      - uses: actions/checkout@v6

      - name: Create nightly tag
        id: tag
        run: |
          TAG="nightly-$(date +'%Y%m%d-%H%M%S')"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Install cross
        run: cargo install cross --force

      - name: Build binary
        run: |
          if [[ "${{ matrix.cargo-tool }}" == "cross" ]]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: "target/${{ matrix.target }}/release/geko*"
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
